### ISSUE TITLE
请问这个有手册吗？

### ISSUE THREAD

**Issue by vayocc** [yuankong11/OCT#1]
我们公司非让我们从java 转ruby 但是ruby那个原生的前端是在没办法做，所以我这边考虑是不是能加入vue ，找了好久都没找到 ruby +vue的实现方法， 如果你这边有教程的话，能不能发一份呢，我看你这个项目确实是我这边想要用的结构

**Comment by yuankong11** [comment]
## 项目生成
以下命令写于20年底，可能存在部分过时。
```bash
# 为了使用webpacker提供的javascript_pack_tag，使用rvm切换rails版本到rails6
# 安装rvm、ruby、rails
sudo apt install gnupg2
gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
\curl -sSL https://get.rvm.io | bash -s stable

rvm install 2.7
gem install rails -v 6.0.3.4
# 新建项目
rails new demo
bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java
bundle install
# 安装yarn(webpacker依赖yarn)、更新node(yarn依赖更新的node)
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt update && sudo apt install yarn
npm i -g n
sudo n stable
# 安装webpacker、webpacker:vue、element-ui、vue-calendar-component
rails webpacker:install
# 执行以下命令会自动生成app/javascript/app.vue、app/javascript/packs/hello_vue.js示例文件
# 此时通过在html.erb的页面文件加入<%= javascript_pack_tag 'hello_vue.js' %>就可以使用vue
rails webpacker:install:vue

yarn config set registry https://registry.npm.taobao.org/
yarn add element-ui
yarn add vue-calendar-component
yarn install
```
## 路由管理
- rails路由[routes](https://github.com/yuankong11/OCT/tree/master/config/routes.rb)将需要渲染到vue的路径都定向到frontend#show上
  - 文件里的frontend#home经rails controller重定向到/app/dashboard，最终命中规则`get 'app/:postfix', to: 'frontend#show'`
- [show.html.erb](https://github.com/yuankong11/OCT/blob/master/app/views/frontend/show.html.erb)使用<%= javascript_pack_tag 'frontend.js' %>导入frontend.js，该js文件跟vue的main.js功能一样，用于渲染整个vue项目，frontend/*下的路由由vue管理。

**Comment by vayocc** [comment]
好的，谢谢，我明天研究研究





项目生成

以下命令写于20年底，可能存在部分过时。

# 为了使用webpacker提供的javascript_pack_tag，使用rvm切换rails版本到rails6# 安装rvm、ruby、rails

sudo apt install gnupg2

gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

\curl -sSL https://get.rvm.io | bash -s stable



rvm install 2.7

gem install rails -v 6.0.3.4

# 新建项目

rails new demo

bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java

bundle install

# 安装yarn(webpacker依赖yarn)、更新node(yarn依赖更新的node)

curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -

echo"deb https://dl.yarnpkg.com/debian/ stable main"| sudo tee /etc/apt/sources.list.d/yarn.list

sudo apt update && sudo apt install yarn

npm i -g n

sudo n stable

# 安装webpacker、webpacker:vue、element-ui、vue-calendar-component

rails webpacker:install

# 执行以下命令会自动生成app/javascript/app.vue、app/javascript/packs/hello_vue.js示例文件# 此时通过在html.erb的页面文件加入<%= javascript_pack_tag 'hello_vue.js' %>就可以使用vue

rails webpacker:install:vue



yarn config set registry https://registry.npm.taobao.org/

yarn add element-ui

yarn add vue-calendar-component

yarn install
路由管理
rails路由routes将需要渲染到vue的路径都定向到frontend#show上
文件里的frontend#home经rails controller重定向到/app/dashboard，最终命中规则get 'app/:postfix', to: 'frontend#show'
show.html.erb使用<%= javascript_pack_tag 'frontend.js' %>导入frontend.js，该js文件跟vue的main.js功能一样，用于渲染整个vue项目，frontend/*下的路由由vue管理。
